---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
  require_chef_omnibus: true
- name: windows-2012r2-standard
  driver_config:
    communicatior: winrm
    box: windows-2012r2-standard
    box_url: http://filer.criteo.prod/boxes/windows-2012r2-standard.box
- name: windows-2016-standard
  transport:
    name: winrm
    elevated: true
    elevated_username: System
    elevated_password: null
  driver_config:
    box: criteo-windows-2016-standard
    box_url: http://filer.criteo.prod/boxes/criteo-windows-2016-standard.box

suites:
- name: default
  run_list: [
    'recipe[wsus-server]',
  ]
  attributes:
    wsus_server:
      subscription:
        automatic_synchronization: false
        classifications:
        - Critical Updates
        - Security Updates
        - Updates
        - Service Packs
        categories:
        - Active Directory
        - Microsoft SQL Server 2012
        - SQL Server 2008 R2
        - Windows Server 2008 R2
        - Windows Server 2012 R2
        - 4e487029-f550-4c22-8b31-9173f3f95786
