language: ruby
cache: bundler
rvm:
- 2.3.0
sudo: false
deploy:
  edge: true
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Package Management
  client_key: .travis/client.pem
  on:
    tags: true
    all_branches: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_279b18d6fd1c_key -iv $encrypted_279b18d6fd1c_iv
  -in .travis/client.pem.enc -out .travis/client.pem -d
